### ISSUE TITLE
Problem with one specific link

### ISSUE THREAD

**Issue by matteocef** [DavidePastore/easy-mac-torrent-download#15]
Used so many time, and is so helpful. Don't know why with this specific link it doesn't work. 

The link is live. Does the script has some problem?

**Comment by DavidePastore** [comment]
Hi @matteocef . What is the link you're using and what is the issue you're facing?

**Comment by DavidePastore** [comment]
This one could be related to https://github.com/gnuns/allOrigins/issues/95

**Comment by matteocef** [comment]
The link is this one: 

https://mac-torrent-download.net/pw.php?UVNaS3FETitCYzJMOU9iMnNPL0dTSk9SbFI1TE1ydTFjVHIvTGN3TWowQT0=

it just load without end. Tried with another link just to check, and it works.

**Comment by matteocef** [comment]
I left it loading, and after several hours, worked. So i don't know which was the problem, but it solved by it self. 


thanks
