### ISSUE TITLE
Password Incorrect

### ISSUE THREAD

**Issue by felipe4000** [DavidePastore/easy-mac-torrent-download#16]
I downloaded Parallels from the website, and used the password tool to get the password. I copied and pasted the password and it was incorrect.

**Comment by DavidePastore** [comment]
Please, ensure that the URL you are pasting in the text field is the right one.

**Comment by felipe4000** [comment]
I tried entering the password to the file on a Windows machine, and it worked completely fine. Maybe it could’ve been because the locked file was a .7z file? Not sure, but in the end, the site worked, and I don’t think my issue was related to your site.
________________________________

**Comment by DavidePastore** [comment]
Nice to know that you were able to fix it on your side.
