### ISSUE TITLE
Webpage is not accessible

### ISSUE THREAD

**Issue by ZDYYY** [DavidePastore/easy-mac-torrent-download#2]
hello
Are you still maintaining this project? Today I found that I cannot open the website
This is a very good project, I hope to solve it

**Comment by DavidePastore** [comment]
Hello @ZDYYY . Yes, the project is still maintained. You can still access the website here: https://davidepastore.github.io/easy-mac-torrent-download/index.html . Are you still facing issues?

**Comment by ZDYYY** [comment]
> Hello @ZDYYY . Yes, the project is still maintained. You can still access the website here: https://davidepastore.github.io/easy-mac-torrent-download/index.html . Are you still facing issues?

Thank you for replying in your busy schedule.
Your project can indeed run, it was my mistake before
I found that the reason why I cannot connect may be related to the proxy mode I chose
I still have another question: how to use the password recovery function, it always shows an error when entering a address

**Comment by DavidePastore** [comment]
@ZDYYY , you have to enter the URL from where you should get the password to extract the archive. The format of the URL should be in the `https://mac-torrent-download.net/pw.php?...` form. What kind of URL are you trying to enter?

**Comment by DavidePastore** [comment]
Duplicated of #6.
