### ISSUE TITLE
La pagina non è raggiungibile

### ISSUE THREAD

**Issue by gigisdb2021** [DavidePastore/easy-mac-torrent-download#8]
Molto utile. Grazie. Il progetto è ancora attivo?

**Comment by DavidePastore** [comment]
Ciao @gigisdb2021 . Grazie per aver aperto questa issue. Effettivamente la pagina non è attualmente funzionante ed è per via di cors-anywhere (in particolare di https://github.com/Rob--W/cors-anywhere/issues/301). Cerco di capire se esistono delle alternative che lo possano sostituire.

**Comment by DavidePastore** [comment]
Ciao @gigisdb2021. Il problema ora è risolto.
